set_pin_physical_constraints -pin_name {NARST} -offset 6 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {EN} -offset 7 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {LO_DIV[2]} -offset 8 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {LO_DIV[1]} -offset 9 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {LO_DIV[0]} -offset 10 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DONE[1]} -offset 11 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {DONE[0]} -offset 12 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {CLK} -offset 13 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {LO_STATE[1]} -offset 14 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {LO_STATE[0]} -offset 15 -layers {M3} -width 0.08 -depth 0 -side 1
set_pin_physical_constraints -pin_name {EXCHOP} -offset 16 -layers {M3} -width 0.08 -depth 0 -side 1


set_pin_physical_constraints -pin_name {SYS_REF} -offset 6 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[34]} -offset 7 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[33]} -offset 8 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[32]} -offset 9 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[31]} -offset 10 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[30]} -offset 11 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[29]} -offset 12 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[28]} -offset 13 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[27]} -offset 14 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[26]} -offset 15 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[25]} -offset 16 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[24]} -offset 17 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[23]} -offset 18 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[22]} -offset 19 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[21]} -offset 20 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[20]} -offset 21 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[19]} -offset 22 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[18]} -offset 23 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[17]} -offset 24 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[16]} -offset 25 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[15]} -offset 26 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[14]} -offset 27 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[13]} -offset 28 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[12]} -offset 29 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[11]} -offset 30 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[10]} -offset 31 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[9]} -offset 32 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[8]} -offset 33 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[7]} -offset 34 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[6]} -offset 35 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[5]} -offset 36 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[4]} -offset 37 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[3]} -offset 38 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[2]} -offset 39 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[1]} -offset 40 -layers {M4} -width 0.08 -depth 0 -side 4
set_pin_physical_constraints -pin_name {PLL_FCW[0]} -offset 41 -layers {M4} -width 0.08 -depth 0 -side 4
